### ISSUE TITLE
How to pipe a variable/data to a command?

### ISSUE THREAD

**Issue by rambhosale** [davidohana/peasyshell#1]
I am trying to save the data into a variable , do some updates and then pass this variable to the pipe.
But cannot get it to work the way I want it
this is the example of what I was trying to achieve

```python
file_list=sh("ls -alh", capture_out=True).stdout

# some updates to file_list by python

length=sh("{} | wc -l", [file_list], capture_out=True).stdout
print(length)

```

**Comment by davidohana** [comment]
The first line in your code already returns the output of `ls`, so you can just use Python code to count lines:

```python
sh("ls -alh", capture_out=True)
length = len(shres.stdout.splitlines())
print(length)
```

Or pipe both commands (must use `shell=True`)

```python
length = int(sh("ls -alh | wc -l", capture_out=True, shell=True).stdout)
print(length)
```

**Comment by rambhosale** [comment]
@davidohana I used ```ls``` as an example 
I was trying to port this bash script https://github.com/miroslavvidovic/rofi-scripts/blob/master/web-search.sh#L53 using python but
having problem piping the data to riofi

**Comment by davidohana** [comment]
Please make sure you use shell=True when using pipes.
Also, look in the examples folder for additional usage info.
